# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import archivo_pb2 as archivo__pb2


class ArchivoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListarArchivos = channel.unary_unary(
                '/archivo.Archivo/ListarArchivos',
                request_serializer=archivo__pb2.ArchivoVacio.SerializeToString,
                response_deserializer=archivo__pb2.ArchivoLista.FromString,
                )
        self.BuscarArchivos = channel.unary_unary(
                '/archivo.Archivo/BuscarArchivos',
                request_serializer=archivo__pb2.ArchivoVacio.SerializeToString,
                response_deserializer=archivo__pb2.ArchivoLista.FromString,
                )


class ArchivoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListarArchivos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarArchivos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArchivoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListarArchivos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarArchivos,
                    request_deserializer=archivo__pb2.ArchivoVacio.FromString,
                    response_serializer=archivo__pb2.ArchivoLista.SerializeToString,
            ),
            'BuscarArchivos': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarArchivos,
                    request_deserializer=archivo__pb2.ArchivoVacio.FromString,
                    response_serializer=archivo__pb2.ArchivoLista.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'archivo.Archivo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Archivo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListarArchivos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/archivo.Archivo/ListarArchivos',
            archivo__pb2.ArchivoVacio.SerializeToString,
            archivo__pb2.ArchivoLista.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BuscarArchivos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/archivo.Archivo/BuscarArchivos',
            archivo__pb2.ArchivoVacio.SerializeToString,
            archivo__pb2.ArchivoLista.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
